risky: false
version: 7
preset: psr2
tab-width: 4
use-tabs: true
disabled:
    - no_blank_lines_after_class_opening
    - no_trailing_whitespace_in_comment
finder:
    exclude:
        - "modules"
        - "node_modules"
        - "storage"
        - "vendor"
    name: "*.php"
    not-name:
        - "*.blade.php"
        - "_ide_helper.php"
